# Generated by Django 2.2.11 on 2020-08-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('authors', models.CharField(max_length=128)),
                ('published_date', models.IntegerField(null=True)),
                ('avarage_rating', models.IntegerField(null=True)),
                ('ratings_count', models.IntegerField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='book_image')),
                ('categories', models.ManyToManyField(related_name='books', to='books.Category')),
            ],
        ),
    ]
